FROM php:7.4-apache

# Copy the WordPress source code into the container
COPY . /var/www/html

# Set the WordPress database environment variables
ARG WORDPRESS_DB_HOST
ARG WORDPRESS_DB_NAME
ARG WORDPRESS_DB_USER
ARG WORDPRESS_DB_PASSWORD

# Run the WordPress installation script
RUN wp core install --url=$WORDPRESS_URL --title=$WORDPRESS_TITLE --admin_user=$WORDPRESS_ADMIN_USER --admin_password=$WORDPRESS_ADMIN_PASSWORD --admin_email=$WORDPRESS_ADMIN_EMAIL

# Set the working directory to the WordPress root directory
WORKDIR /var/www/html

# Expose port 80 for Apache
EXPOSE 80

# Start Apache
CMD ["apache2ctl", "-D", "FOREGROUND"]
Use code with caution. Learn more

# Build the Docker image
#docker build -t my-wordpress-image .

# Tag the image
#docker tag my-wordpress-image <your-docker-hub-username>/my-wordpress-image

# Push the image to Docker Hub
#docker push <your-docker-hub-username>/my-wordpress-image

# Run the container
#docker run -d -p 80:80 --name my-wordpress-container <your-docker-hub-username>/my-wordpress-image


#Set the WordPress database connection string
#docker exec my-wordpress wp config set DB_HOST $RDS_ENDPOINT
#docker exec my-wordpress wp config set DB_USER my-rds-username
#docker exec my-wordpress wp config set DB_PASSWORD my-rds-password
#docker exec my-wordpress wp config set DB_NAME my-rds-database

#Setup the WordPress:

#docker exec my-wordpress wp core install --url http://localhost --title My WordPress Site --admin_user admin --admin_password my-wordpress-password
